
document.querySelector("#views-placeholder > div").style.background = "#A1019D"
document.querySelector("#views-placeholder > div").style.backgroundImage = "url(https://student.zav.cz/dist/4b980caddd636d7aaf798f3a4a227502.png)"
document.querySelector("#views-placeholder > div").style.backgroundSize = "350px"
document.querySelector("#views-placeholder > div > div > div:nth-child(1) > div.col.d-flex.flex-row > h1 > img").src = "https://raw.githubusercontent.com/honzawashere/zav-js/main/zav-logo-barevne-student-cs.png"
document.querySelector("#views-placeholder > div > div > div:nth-child(2) > div:nth-child(1) > form > input").style.backgroundColor = "#A1019D"
document.querySelector("#views-placeholder > div > div > div:nth-child(2) > div:nth-child(1) > form > input").style.borderColor = "#A1019D"
document.querySelector("#views-placeholder > div > div > div:nth-child(2) > div:nth-child(1) > form > input").style.color = "white"
document.querySelector("#views-placeholder > div:nth-child(1) > div > div:nth-child(1) > div:nth-child(2) > div > button").style.backgroundColor = "#A1019D"
document.querySelector("#views-placeholder > div:nth-child(1) > div > div:nth-child(1) > div:nth-child(2) > div > button").style.borderColor = "#A1019D"
document.querySelector("#views-placeholder > div:nth-child(1) > div > div:nth-child(1) > div:nth-child(2) > div > button").style.color = "white"
document.querySelector("#views-placeholder > div > div > div.row.flex-grow-1.align-items-center.justify-content-center > div").style.color = "#A1019D !important"
document.querySelector("#views-placeholder > div > div > div:nth-child(2) > div.col.d-flex.flex-column.d-none.d-lg-flex > div:nth-child(2) > p:nth-child(2) > a").style.color = "#A1019D !important"